export const STUDENT_SIGNUP_URL=BASE_URL + '/api/v1/student'
export const ADMIN_SIGNUP_URL=BASE_URL + '/api/v1/admin'
export const STUDENT_SIGNIN_URL=BASE_URL + '/api/v1/auth/jwt'
export const ADMIN_SIGNIN_URL=BASE_URL + '/api/v1/admin/auth/jwt'
export const BASE_URL='https://panicky-duck-earmuffs.cyclic.app'
export const LOCAL_BASE='http://localhost:8000'